POST http://localhost:8080/rest/score
Content-Type: application/json

{
  "player": "vajcak",
  "game":"pictureslidingpuzzle",
  "points": 55,
  "playedOn": "2019-03-25T15:40:33"
}

###



POST http://localhost:8080/rest/comment
Content-Type: application/json

{
  "player": "kiko",
  "game":"pictureslidingpuzzle",
  "comment": "najsamlepsa hra",
  "commentedOn": "2019-03-25T15:40:33"
}

###
POST http://localhost:8080/rest/rating
Content-Type: application/json

{
  "player": "kiko",
  "game":"pictureslidingpuzzle",
  "rating": 2,
  "ratedon": "2019-03-25T15:40:33"
}

###
GET http://localhost:8080/rest/score/pictureslidingpuzzle
Content-Type: application/json

###
GET http://localhost:8080/rest/rating/pictureslidingpuzzle
Content-Type: application/json

###
GET http://localhost:8080/rest/comment/pictureslidingpuzzle
Content-Type: application/json

###
