POST http://localhost:8080/rest/score
Content-Type: application/json

{
  "player": "hvvg",
  "game":"pictureslidingpuzzle",
  "points": 420,
  "playedOn": "2019-03-25T15:40:33"
}

###



POST http://localhost:8080/rest/comment
Content-Type: application/json

{
  "player": "dfsafas",
  "game":"pictureslidingpuzzle",
  "comment": "ddasd",
  "commentedOn": "2019-03-25T15:40:33"
}

###
POST http://localhost:8080/rest/rating
Content-Type: application/json

{
  "player": "das",
  "game":"pictureslidingpuzzle",
  "rating": 3,
  "ratedon": "2019-03-25T15:40:33"
}

###
GET http://localhost:8080/rest/score/pictureslidingpuzzle
Content-Type: application/json

###
GET http://localhost:8080/rest/rating/pictureslidingpuzzle/kiko
Content-Type: application/json

###

GET http://localhost:8080/rest/rating/pictureslidingpuzzle
Content-Type: application/json

###
GET http://localhost:8080/rest/comment/pictureslidingpuzzle
Content-Type: application/json

###
